# Generated by Django 3.0.2 on 2020-03-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
