# Generated by Django 3.0.2 on 2020-03-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_list_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='pub_date',
        ),
    ]
