# Generated by Django 3.0.2 on 2020-03-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_list_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
