# Generated by Django 3.0.2 on 2020-03-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20200321_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='to_do_list',
            new_name='text',
        ),
    ]
